package ir.ifarbod.gradle

import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.TaskAction
import java.io.File

@CacheableTask
open class XMakeCleanTask : XMakeTask() {
    init {
        group = XMAKE_GROUP
        description = "Clean files generated by XMake"
    }

    internal fun commandLine(): List<String> {
        val context = context()
        return buildList {
            addAll(listOf(context.program, "clean"))
            addLogLevel(context.logLevel)
            addAll(context.targets)
        }
    }

    internal fun uninstallCommandLine(script: File): List<String> {
        val context = context()
        return buildList {
            addAll(listOf(context.program, "lua"))
            addLogLevel(context.logLevel)
            add(script.absolutePath)
            addAll(listOf("-o", context.nativeLibsDirectory.absolutePath))
            addAll(listOf("-a", checkNotNull(context.buildArch)))
            add("-c")
            addAll(context.targets)
        }
    }

    @TaskAction
    fun clean() {
        val context = taskContext ?: return
        requireProjectFile()
        XMakeExecutor(context.logger).exec(commandLine(), context.projectDirectory)
        XMakeExecutor(context.logger)
            .exec(uninstallCommandLine(extractInstallScript(context)), context.projectDirectory)
    }
}
